module

public import RequestProject.Semantics.GirardQuantale

/-!
# *-autonomous categories: the categorical model of linear logic

* `CategoryTheory.doubleDualMap`, `CategoryTheory.StarAutonomous`: Barr's definition. A
  **\*-autonomous category** is a symmetric monoidal closed category `C` with a *dualizing
  object* `⊥` such that for every `A` the canonical map `A ⟶ (A ⊸ ⊥) ⊸ ⊥` is an isomorphism
  (the categorical **duality involution** / law of double negation).
* `CategoryTheory.StarAutonomous.par`, `CategoryTheory.StarAutonomous.linearDistrib`: in a
  symmetric monoidal closed category with an object `⊥`, put `A* = A ⊸ ⊥` and
  `A ⅋ B = (A* ⊗ B*)*`; we construct the **linear distribution**
  `δ : A ⊗ (B ⅋ C) ⟶ (A ⊗ B) ⅋ C` and `StarAutonomous.linearDistrib'`,
  `δ' : (A ⅋ B) ⊗ C ⟶ A ⅋ (B ⊗ C)`, linking the two tensors `⊗` and `⅋`: these are the
  structure maps of a *linearly distributive category* (we construct the maps; the
  coherence equations of linearly distributive categories are not formalised).
* `GirardQuantale.instStarAutonomous`: **every Girard quantale is a (thin) \*-autonomous
  category** (objects = elements, a unique morphism `a ⟶ b` iff `a ≤ b`, `⊗ = *`,
  `⊸` = residuation, dualizing object `d`). Being a complete lattice it moreover has all
  products and coproducts (`&`, `⊕` and their units), see `GirardQuantale.hasLimits`.
* `GirardQuantale.polycategory_representable` and `ILLe.ILC.representable`:
  **representability**: in a Girard quantale, a polymorphism `Γ → Δ` is the same as a
  morphism `⊗Γ → ⅋Δ`; likewise, in the syntactic polycategory of **ILC**-provability (the
  free polycategory generated by the formulas), `Γ ⊢ Δ` is provable iff
  `⊗Γ ⊢ ⅋Δ` is. This is the sense in which \*-autonomous categories are the *representable*
  polycategories.
-/

@[expose] public section

universe u v

open CategoryTheory MonoidalCategory

namespace CategoryTheory

variable {C : Type u} [Category.{v} C] [MonoidalCategory C] [SymmetricCategory C]
  [MonoidalClosed C]

/-- The canonical map `A ⟶ (A ⊸ d) ⊸ d` of a symmetric monoidal closed category. -/
def doubleDualMap (d A : C) : A ⟶ (ihom ((ihom A).obj d)).obj d :=
  MonoidalClosed.curry ((β_ ((ihom A).obj d) A).hom ≫ (ihom.ev A).app d)

variable (C) in
/-- **\*-autonomous category** (Barr): a symmetric monoidal closed category with a dualizing
object `⊥`, i.e. such that every canonical map `A ⟶ (A ⊸ ⊥) ⊸ ⊥` is an isomorphism. -/
class StarAutonomous where
  /-- the dualizing object `⊥` -/
  dualizing : C
  /-- duality is involutive: `A ≅ A**` canonically -/
  isIso_doubleDualMap : ∀ A : C, IsIso (doubleDualMap dualizing A)

namespace StarAutonomous

/-- The dual `A* = A ⊸ d`. -/
def dual (d A : C) : C := (ihom A).obj d

/-- The **par** (cotensor) `A ⅋ B = (A* ⊗ B*)*`. -/
def par (d A B : C) : C := dual d (dual d A ⊗ dual d B)

/-- evaluation `A ⊗ A* ⟶ d` -/
def ev (d A : C) : A ⊗ dual d A ⟶ d := (ihom.ev A).app d

/-- the map `(A ⊗ B)* ⊗ A ⟶ B*` -/
def dualTensorAux (d A B : C) : dual d (A ⊗ B) ⊗ A ⟶ dual d B :=
  MonoidalClosed.curry
    (B ◁ (β_ (dual d (A ⊗ B)) A).hom ≫ (α_ B A (dual d (A ⊗ B))).inv ≫
      (β_ B A).hom ▷ dual d (A ⊗ B) ≫ ev d (A ⊗ B))

/-- The **linear distribution** `δ : A ⊗ (B ⅋ C) ⟶ (A ⊗ B) ⅋ C`, linking the two tensors
`⊗` and `⅋` of a symmetric monoidal closed category with an object `d`. -/
def linearDistrib (d A B C' : C) : A ⊗ par d B C' ⟶ par d (A ⊗ B) C' :=
  MonoidalClosed.curry <|
    (α_ (dual d (A ⊗ B)) (dual d C') (A ⊗ par d B C')).hom ≫
    dual d (A ⊗ B) ◁ (α_ (dual d C') A (par d B C')).inv ≫
    dual d (A ⊗ B) ◁ ((β_ (dual d C') A).hom ▷ par d B C') ≫
    dual d (A ⊗ B) ◁ (α_ A (dual d C') (par d B C')).hom ≫
    (α_ (dual d (A ⊗ B)) A (dual d C' ⊗ par d B C')).inv ≫
    dualTensorAux d A B ▷ (dual d C' ⊗ par d B C') ≫
    (α_ (dual d B) (dual d C') (par d B C')).inv ≫
    ev d (dual d B ⊗ dual d C')

/-- the map `(B ⊗ C)* ⊗ C ⟶ B*` -/
def dualTensorAux' (d B C' : C) : dual d (B ⊗ C') ⊗ C' ⟶ dual d B :=
  MonoidalClosed.curry
    (B ◁ (β_ (dual d (B ⊗ C')) C').hom ≫ (α_ B C' (dual d (B ⊗ C'))).inv ≫ ev d (B ⊗ C'))

/-- The other **linear distribution** `δ' : (A ⅋ B) ⊗ C ⟶ A ⅋ (B ⊗ C)`. -/
def linearDistrib' (d A B C' : C) : par d A B ⊗ C' ⟶ par d A (B ⊗ C') :=
  MonoidalClosed.curry <|
    (α_ (dual d A) (dual d (B ⊗ C')) (par d A B ⊗ C')).hom ≫
    dual d A ◁ (dual d (B ⊗ C') ◁ (β_ (par d A B) C').hom) ≫
    dual d A ◁ (α_ (dual d (B ⊗ C')) C' (par d A B)).inv ≫
    dual d A ◁ (dualTensorAux' d B C' ▷ par d A B) ≫
    (α_ (dual d A) (dual d B) (par d A B)).inv ≫
    ev d (dual d A ⊗ dual d B)

end StarAutonomous

end CategoryTheory

/-! ## Girard quantales are \*-autonomous categories -/

namespace GirardQuantale

open CommQuantale

variable {Q : Type u} [GirardQuantale Q]

/-- The monoidal structure `⊗ = *` on (the thin category of) a Girard quantale. -/
instance instMonoidalCategory : MonoidalCategory Q where
  tensorObj a b := a * b
  whiskerLeft _ _ _ f := homOfLE (mul_le_mul' le_rfl (leOfHom f))
  whiskerRight f _ := homOfLE (mul_le_mul' (leOfHom f) le_rfl)
  tensorHom f g := homOfLE (mul_le_mul' (leOfHom f) (leOfHom g))
  tensorUnit := 1
  associator a b c := eqToIso (mul_assoc a b c)
  leftUnitor a := eqToIso (one_mul a)
  rightUnitor a := eqToIso (mul_one a)
  tensorHom_def _ _ := rfl
  id_tensorHom_id _ _ := rfl
  tensorHom_comp_tensorHom _ _ _ _ := rfl
  whiskerLeft_id _ _ := rfl
  id_whiskerRight _ _ := rfl
  associator_naturality _ _ _ := rfl
  leftUnitor_naturality _ := rfl
  rightUnitor_naturality _ := rfl
  pentagon _ _ _ _ := rfl
  triangle _ _ := rfl

instance instSymmetricCategory : SymmetricCategory Q where
  braiding a b := eqToIso (mul_comm a b)
  braiding_naturality_right _ _ _ _ := rfl
  braiding_naturality_left _ _ := rfl
  hexagon_forward _ _ _ := rfl
  hexagon_reverse _ _ _ := rfl
  symmetry _ _ := rfl

lemma limp_mono_right (a : Q) : Monotone (limp a) := fun _ _ h =>
  le_limp_iff.2 ((le_limp_iff.1 le_rfl).trans h)

/-- Closed structure: the internal hom is the residuation `a ⊸ b`. -/
instance instMonoidalClosed : MonoidalClosed Q where
  closed a :=
    { rightAdj := (limp_mono_right a).functor
      adj := Adjunction.mkOfHomEquiv
        { homEquiv := fun X Y =>
            { toFun := fun f => homOfLE (le_limp_iff.2 (by
                rw [mul_comm]; exact leOfHom f))
              invFun := fun g => homOfLE (by
                change a * X ≤ Y
                rw [mul_comm]; exact le_limp_iff.1 (leOfHom g))
              left_inv := fun _ => rfl
              right_inv := fun _ => rfl }
          homEquiv_naturality_left_symm := fun _ _ => rfl
          homEquiv_naturality_right := fun _ _ => rfl } }

lemma ihom_obj (a b : Q) : (ihom a).obj b = limp a b := rfl

/-- **Every Girard quantale is a \*-autonomous category**, with dualizing object the
dualizing element `d`: the canonical map `a ⟶ (a ⊸ d) ⊸ d` is invertible by the law of
double negation. -/
instance instStarAutonomous : StarAutonomous Q where
  dualizing := dualizing
  isIso_doubleDualMap a :=
    ⟨⟨homOfLE (le_of_eq (lneg_lneg' a)), Subsingleton.elim _ _, Subsingleton.elim _ _⟩⟩

/-- A Girard quantale, being a complete lattice, has all (small) limits and colimits; in
particular products (`&`, with unit the top element) and coproducts (`⊕`, with unit the
bottom element). -/
example : Limits.HasLimits Q := inferInstance
example : Limits.HasColimits Q := inferInstance

/-! ## Representability -/

/-- `⊗Γ`: the product of a multiset in the quantale. -/
def tensorAll (Γ : Multiset Q) : Q := Γ.prod

/-- `⅋Δ = (∏ Δ⊥)⊥`. -/
def parAll (Δ : Multiset Q) : Q := lneg (Δ.map lneg).prod

/-- **Representability of the polycategory of a Girard quantale**: polymorphisms `Γ → Δ`
correspond to morphisms `⊗Γ → ⅋Δ`. -/
theorem polycategory_representable (Γ Δ : Multiset Q) :
    (toThinPolycategory Q).Hom Γ Δ ↔ (toThinPolycategory Q).Hom {tensorAll Γ} {parAll Δ} := by
  simp only [toThinPolycategory, Multiset.prod_singleton, Multiset.map_singleton, tensorAll,
    parAll, lneg_lneg]

end GirardQuantale

/-! ## Representability of the syntactic polycategory of ILC -/

namespace ILLe

open Formula

variable {α : Type u} {ι : Bool}

/-- `⊗[A₁, …, Aₙ] = A₁ ⊗ (⋯ ⊗ (Aₙ ⊗ ⊤))` (`⊤` is the unit of `⊗` in the paper's notation). -/
def tensorList : List (Formula α) → Formula α
  | [] => top
  | A :: l => tensor A (tensorList l)

/-- `⅋[B₁, …, Bₘ] = B₁ ⅋ (⋯ ⅋ (Bₘ ⅋ ⊥))`. -/
def parList : List (Formula α) → Formula α
  | [] => bot
  | B :: l => par B (parList l)

namespace ILC

lemma tensorList_left (l : List (Formula α)) :
    ∀ {Θ Γ : Multiset (Formula α)}, ILC ι ((l : Multiset (Formula α)) + Θ) Γ →
      ILC ι (tensorList l ::ₘ Θ) Γ := by
  induction l with
  | nil => intro Θ Γ h; exact topL (by simpa using h)
  | cons A l ih =>
    intro Θ Γ h
    have h' : ILC ι ((l : Multiset (Formula α)) + (A ::ₘ Θ)) Γ :=
      h.cast' (by rw [← Multiset.cons_coe, Multiset.cons_add, Multiset.add_cons]) rfl
    exact tensorL ((ih h').cast' (Multiset.cons_swap _ _ _) rfl)

lemma parList_right (l : List (Formula α)) :
    ∀ {Δ Θ : Multiset (Formula α)}, ILC ι Δ ((l : Multiset (Formula α)) + Θ) →
      ILC ι Δ (parList l ::ₘ Θ) := by
  induction l with
  | nil => intro Δ Θ h; exact botR (by simpa using h)
  | cons B l ih =>
    intro Δ Θ h
    have h' : ILC ι Δ ((l : Multiset (Formula α)) + (B ::ₘ Θ)) :=
      h.cast' rfl (by rw [← Multiset.cons_coe, Multiset.cons_add, Multiset.add_cons])
    exact parR ((ih h').cast' rfl (Multiset.cons_swap _ _ _))

lemma tensorList_right (l : List (Formula α)) :
    ILC ι (l : Multiset (Formula α)) {tensorList l} := by
  induction l with
  | nil => exact topR
  | cons A l ih =>
    exact (tensorR (Γ₁ := 0) (Γ₂ := 0) (id A) ih).cast' (by simp) (by simp [tensorList])

lemma parList_left (l : List (Formula α)) :
    ILC ι {parList l} (l : Multiset (Formula α)) := by
  induction l with
  | nil => exact botL
  | cons B l ih =>
    exact (parL (Δ₁ := 0) (Δ₂ := 0) (id B) ih).cast' (by simp [parList]) (by simp)

/-- **Representability of the polycategory of ILC-provability**: `Γ ⊢ Δ` is provable iff
`⊗Γ ⊢ ⅋Δ` is. -/
theorem representable (Γ Δ : List (Formula α)) :
    ILC ι (Γ : Multiset (Formula α)) (Δ : Multiset (Formula α)) ↔
      ILC ι {tensorList Γ} {parList Δ} := by
  constructor
  · intro h
    have h1 := tensorList_left Γ (Θ := 0) (h.cast' (by simp) rfl)
    exact parList_right Δ (Θ := 0) (h1.cast' rfl (by simp))
  · intro h
    have h1 := cut (Γ := 0) (Δ' := 0) (tensorList_right Γ) h
    have h1' : ILC ι (Γ : Multiset (Formula α)) {parList Δ} := h1.cast' (by simp) (by simp)
    have h2 := cut (Γ := 0) (Δ' := 0) h1' (parList_left Δ)
    exact h2.cast' (by simp) (by simp)

end ILC

end ILLe

end
